#index:
#    path: /
#    controller: App\Controller\DefaultController::index

salle_tp:
    resource: routes/salle/routes.yaml
    prefix: /salle

essai_tp:
    resource: routes/essai/routes.yaml
    prefix: /essai
# salle_tp_accueil:
#     path: /accueil
#     controller: App\Controller\SalleController::accueil

# salle_tp_afficher:
#     path: /afficher/{numero}
#     controller: App\Controller\SalleController::afficher
#     requirements:
#         numero: '\d{1,2}'
